CREATE OR REPLACE PROCEDURE "PACKAGE"."ALLOCATE_TRADE"
(
P_TRADE_ID varchar2,
P_TRADE_QUANTITY number,
P_TRADE_DATE date,
P_TRADE_SIDE varchar2,
P_TRADE_STATUS varchar2,
P_TRADE_PRICE number,
P_INSTRUMENT_ID varchar2
)

IS

begin

UPDATE TEST_TRADE
SET
    TRADE_QUANTITY = P_TRADE_QUANTITY,
    TRADE_DATE = P_TRADE_DATE,
    TRADE_SIDE = P_TRADE_SIDE,
    TRADE_STATUS = P_TRADE_STATUS,
    TRADE_PRICE = P_TRADE_PRICE
WHERE TRADE_ID = T_TRADE_ID;

end;

CREATE OR REPLACE PROCEDURE "PACKAGE"."CREATE_TRADE"
(
P_TRADE_ID varchar2,
P_TRADE_QUANTITY number,
P_TRADE_DATE date,
P_TRADE_SIDE varchar2,
P_TRADE_STATUS varchar2,
P_TRADE_PRICE number,
P_INSTRUMENT_ID varchar2,
P_TRADE_PRICE number
)

IS

begin

INSERT INTO TEST_TRADE (TRADE_ID, TRADE_QUANTITY, TRADE_DATE, TRADE_SIDE, TRADE_STATUS, TRADE_PRICE, INSTRUMENT_ID)
VALUES
(
    SEQ.nextval, P_TRADE_QUANTITY, P_TRADE_DATE, P_TRADE_SIDE, P_TRADE_STATUS, P_TRADE_PRICE, P_INSTRUMENT_ID
);

end;

CREATE OR REPLACE PROCEDURE "PACKAGE"."ALLOCATE_TRADE_ALLOCATION"
(
P_TRADE_ID varchar2,
P_TRADE_ALLOCATION_QUANTITY number,
P_ACCOUNT_ID varchar2
)

IS

begin

INSERT INTO TEST_TRADE_ALLOCATION (TRADE_ALLOCATION_ID, TRADE_ID, TRADE_ALLOCATION_QUANTITY, ACCOUNT_ID)
VALUES
(
    SEQ.nextval, P_TRADE_ID, P_TRADE_ALLOCATION_QUANTITY, P_ACCOUNT_ID
);

end;