CREATE TABLE TEST_PROJECT.TEST_ACCOUNT  ( 
	ACCOUNT_ID        	VARCHAR2(500) NOT NULL,
	ACCOUNT_SHORT_NAME	VARCHAR2(25) NOT NULL,
	ACCOUNT_LONG_NAME 	VARCHAR2(500) NOT NULL,
	ACCOUNT_NAV       	NUMBER(15,5) NOT NULL,
	BUSINESS_DATE     	DATE NOT NULL,
	CONSTRAINT RAP_ACCOUNT_PK PRIMARY KEY(ACCOUNT_ID)
	NOT DEFERRABLE
USING INDEX 
TABLESPACE DATA_S02 PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( BUFFER_POOL DEFAULT )
LOGGING 
)
TABLESPACE DATA_S02 NOCOMPRESS PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
NOCACHE 
MONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
GO

CREATE TABLE TEST_PROJECT.TEST_INSTRUMENT  ( 
	INSTRUMENT_ID       	NUMBER(15,5) NOT NULL,
	SECURITY_INDENTIFIER	VARCHAR2(100) NOT NULL,
	ASSET_TYPE          	VARCHAR2(100) NOT NULL,
	CONSTRAINT TEST_INSTRUMENT_PK PRIMARY KEY(INSTRUMENT_ID)
	NOT DEFERRABLE
USING INDEX 
TABLESPACE DATA_S02 PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( BUFFER_POOL DEFAULT )
LOGGING 
)
TABLESPACE DATA_S02 NOCOMPRESS PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
NOCACHE 
MONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
GO

CREATE TABLE TEST_PROJECT.TEST_TRADE  ( 
	TRADE_ID              	NUMBER(15,5) NOT NULL,
	TRADE_DATE            	DATE NULL,
	QUANTITY              	NUMBER(15,5) NULL,
	PRICE                 	NUMBER(15,5) NULL,
	TRADE_STATUS          	VARCHAR2(500) NULL,
	ADDED_ENTRY_DATETIME  	DATE NULL,
	LAST_MODIFIED_DATETIME	DATE NULL,
	ADDED_BY              	VARCHAR2(50) NULL,
	LAST_MODIFIED_BY      	VARCHAR2(50) NULL,
	TRADE_SIDE            	VARCHAR2(50) NULL,
	INSTRUMENT_ID         	NUMBER(15,5) NULL,
	CONSTRAINT RAP_TRADE_PK PRIMARY KEY(TRADE_ID)
	NOT DEFERRABLE
USING INDEX 
TABLESPACE DATA_S02 PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( BUFFER_POOL DEFAULT )
LOGGING 
)
TABLESPACE DATA_S02 NOCOMPRESS PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
NOCACHE 
MONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
GO
ALTER TABLE TEST_PROJECT.TEST_TRADE
	ADD ( CONSTRAINT RAP_TRADE_FK
	FOREIGN KEY(INSTRUMENT_ID)
	REFERENCES TEST_PROJECT.TEST_INSTRUMENT(INSTRUMENT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
GO


CREATE TABLE TEST_PROJECT.TEST_TRADE_ALLOCATION  ( 
	TRADE_ALLOCATION_ID      	NUMBER(15,5) NOT NULL,
	TRADE_ID                 	NUMBER(15,5) NOT NULL,
	ACCOUNT_ID               	VARCHAR2(500) NOT NULL,
	TRADE_ALLOCATION_QUANTITY	VARCHAR2(25) NOT NULL,
	CONSTRAINT TEST_TRADE_ALLOCATION_PK PRIMARY KEY(TRADE_ALLOCATION_ID)
	NOT DEFERRABLE
USING INDEX 
TABLESPACE DATA_S02 PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( BUFFER_POOL DEFAULT )
LOGGING 
)
TABLESPACE DATA_S02 NOCOMPRESS PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
NOCACHE 
MONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
GO
ALTER TABLE TEST_PROJECT.TEST_TRADE_ALLOCATION
	ADD ( CONSTRAINT TEST_TRADE_ALLOCATION_FK2
	FOREIGN KEY(ACCOUNT_ID)
	REFERENCES TEST_PROJECT.TEST_ACCOUNT(ACCOUNT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
GO
ALTER TABLE TEST_PROJECT.TEST_TRADE_ALLOCATION
	ADD ( CONSTRAINT TEST_TRADE_ALLOCATION_FK1
	FOREIGN KEY(TRADE_ID)
	REFERENCES TEST_PROJECT.TEST_TRADE(TRADE_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
GO
